name: robot-env
channels:
- conda-forge
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/menpo/
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
- defaults
dependencies:
- ffmpeg
- python = 3
- jupyter
- matplotlib
- pandas
- numpy
- scikit-learn = 0.18.0
- pip:
  - tqdm
  - imageio
  - pillow
  - opencv-python
